let P=[];
async function load(){try{P=await(await fetch("data/products.json")).json();render();select("pv")}catch(e){console.error("No se pudo cargar data/products.json",e)}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function select(id){const p=P.find(x=>x.id===id);if(!p)return;const put=(i,v)=>{const el=document.getElementById(i);if(el)el.textContent=v};put("num",p.n);put("cat",p.cat);put("name",p.name);put("brand",p.brand);put("desc",p.desc);const s=document.getElementById("specs");if(s)s.innerHTML=p.spec.map(x=>`<div><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join("");put("prods",(p.families||[]).join(" · "));put("catalog-note",p.catalog||"");document.querySelectorAll("[data-component]").forEach(el=>el.classList.toggle("selected",el.dataset.component===id));}
function render(f="all"){const c=document.getElementById("cards");if(!c)return;c.innerHTML=P.filter(p=>f==="all"||(p.tags||[]).includes(f)).map(p=>`<article class="card" onclick="select('${p.id}');document.querySelector('#explorer').scrollIntoView({behavior:'smooth'})"><div class="pic ${p.tags?.includes('cable')?'cable-pic':''}"></div><label>${esc(p.cat)}</label><h3>${esc(p.name)}</h3><p>${esc((p.families||[]).slice(0,3).join(" · "))}</p><small>${esc(p.brand)}</small></article>`).join("")}
function view(v,b){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");const st=document.getElementById("stage");if(st)st.classList.toggle("top",v==="top")}
function flow(){const e=document.querySelector(".flow");if(e)e.classList.toggle("off")}
function openContact(){document.getElementById("modal")?.classList.add("show")}
function closeContact(){document.getElementById("modal")?.classList.remove("show")}
function sendInquiry(){const n=document.getElementById("contactName").value;const em=document.getElementById("contactEmail").value;const topic=document.getElementById("contactTopic").value;const msg=document.getElementById("contactMessage").value;const body=encodeURIComponent(`Nombre / empresa: ${n}\nCorreo: ${em}\nTema: ${topic}\nProyecto: ${msg}`);location.href=`mailto:?subject=${encodeURIComponent("Consulta comercial solar - "+topic)}&body=${body}`}
document.addEventListener("DOMContentLoaded",()=>{load();document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.f)});document.querySelectorAll(".equip").forEach(b=>b.addEventListener("click",()=>select(b.dataset.component)))})